In [1]:
import pandas as pd
data = pd.read_csv('/Users/muhammadzuamaalamin/Documents/percobaancvd/datasetfix/heart_disease_new_dataset1.csv')
data

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_VEGRES1,_FRUTSU1,_VEGESU1,_FRTLT1A,_VEGLT1A,_FRT16A,_VEG23A,_FRUITE1,_VEGETE1,CVD_LABEL
0,1.0,1.0,b'01192021',b'01',b'19',b'2021',1100.0,b'2021000001',2.021000e+09,1.0,...,1.0,100.0,214.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
1,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000002',2.021000e+09,1.0,...,1.0,100.0,128.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,CHD Only
2,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000003',2.021000e+09,1.0,...,1.0,100.0,71.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,CHD Only
3,1.0,1.0,b'01172021',b'01',b'17',b'2021',1100.0,b'2021000004',2.021000e+09,1.0,...,1.0,114.0,165.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
4,1.0,1.0,b'01152021',b'01',b'15',b'2021',1100.0,b'2021000005',2.021000e+09,1.0,...,1.0,100.0,258.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,MI + Stroke
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,78.0,12.0,b'01062022',b'01',b'06',b'2022',1100.0,b'2021001381',2.021001e+09,NaN,...,1.0,157.0,393.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
438689,78.0,12.0,b'01122022',b'01',b'12',b'2022',1100.0,b'2021001382',2.021001e+09,NaN,...,1.0,200.0,157.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
438690,78.0,12.0,b'12212021',b'12',b'21',b'2021',1100.0,b'2021001383',2.021001e+09,NaN,...,1.0,200.0,143.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
438691,78.0,12.0,b'01112022',b'01',b'11',b'2022',1100.0,b'2021001384',2.021001e+09,NaN,...,1.0,100.0,156.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt


In [2]:
data.isnull().sum()

_STATE       0
FMONTH       0
IDATE        0
IMONTH       0
IDAY         0
            ..
_FRT16A      0
_VEG23A      0
_FRUITE1     0
_VEGETE1     0
CVD_LABEL    0
Length: 304, dtype: int64

In [3]:
data['CVD_LABEL'].value_counts()

CVD_LABEL
Healt                391852
Stroke Only           11518
CHD Only              11048
Heart Attack Only     10295
MI + CHD               8285
MI + Stroke            2137
All Three              2114
CHD + Stroke           1444
Name: count, dtype: int64

In [4]:
miss = data.isnull().mean().sort_values(ascending=False) * 100
miss

HAVECFS      100.000000
WORKCFS      100.000000
TOLDCFS      100.000000
COLGHOUS      99.993162
COLGSEX       99.993162
                ...    
_TOTINDA       0.000000
_HCVU652       0.000000
_HLTHPLN       0.000000
_MENT14D       0.000000
CVD_LABEL      0.000000
Length: 304, dtype: float64

In [5]:
high = (miss >= 25).sum()
high

165

In [6]:
# Hapus kolom dengan missing value >= 50%
threshold = 25
cols_to_drop = miss[miss > threshold].index
data1 = data.drop(columns=cols_to_drop)

print(f"Kolom yang dihapus ({len(cols_to_drop)}): {list(cols_to_drop)}")
print(f"Shape sebelum: {data.shape}")
print(f"Shape sesudah: {data1.shape}")

Kolom yang dihapus (165): ['HAVECFS', 'WORKCFS', 'TOLDCFS', 'COLGHOUS', 'COLGSEX', 'SIGMTES1', 'MEDSHEPB', 'TRETHEPC', 'PRIRHEPC', 'HAVEHEPC', 'VCLNTES1', 'SDNATES1', 'BLDSTFIT', 'CSRVCTL2', 'LASTSIG4', 'PCSTALK', 'PCPSARS2', 'PSATIME1', 'STOLTEST', 'CCLGHOUS', 'CDHELP', 'STOOLDN1', 'VIRCOLO1', 'SMALSTOL', 'PSATEST1', 'HPVADSHT', 'CSRVINST', 'LOADULK2', 'CDDISCUS', 'CDSOCIAL', 'CDASSIST', 'CDHOUSE', 'CSRVCLIN', 'CSRVDEIN', 'CSRVINSR', 'CSRVRTRN', 'CSRVSUM', 'CSRVDOC1', 'COLNTES1', 'CRVCLPAP', 'CRVCLHPV', 'CRVCLCNC', 'COLNSIGM', 'CASTHNO2', 'CSRVTRT3', 'HOWLONG', 'COLNCNCR', 'HADSIGM4', 'CSRVPAIN', 'HADHYST2', 'CERVSCRN', 'HADMAM', 'CNCRTYP1', 'CNCRAGE', 'CNCRDIFF', 'HAVEHEPB', 'TOLDHEPC', 'LCSNUMCG', 'LCSLAST', 'GUNLOAD', 'LCSFIRST', 'HPVADVC4', 'RSNMRJN2', 'USEMRJN3', 'SHINGLE2', 'TETANUS1', 'FEETCHK', 'DIABEDU', 'DIABEYE', 'EYEEXAM1', 'CHKHEMO3', 'DOCTDIAB', 'FEETCHK3', 'INSULIN1', 'BLDSUGAR', 'STOPSMK2', 'LCSCTSCN', 'FIREARM5', 'NUMPHON3', 'CIMEMLOS', 'CRGVALZD', 'DRADVISE', 'WTCHSA

In [7]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Columns: 139 entries, _STATE to CVD_LABEL
dtypes: float64(133), object(6)
memory usage: 465.2+ MB


In [8]:
# Cara 1 - Print list kolom yang dihapus
cols_to_drop = miss[miss >= 25].index
print(f"Kolom yang dihapus ({len(cols_to_drop)}):")
print(list(cols_to_drop))

Kolom yang dihapus (165):
['HAVECFS', 'WORKCFS', 'TOLDCFS', 'COLGHOUS', 'COLGSEX', 'SIGMTES1', 'MEDSHEPB', 'TRETHEPC', 'PRIRHEPC', 'HAVEHEPC', 'VCLNTES1', 'SDNATES1', 'BLDSTFIT', 'CSRVCTL2', 'LASTSIG4', 'PCSTALK', 'PCPSARS2', 'PSATIME1', 'STOLTEST', 'CCLGHOUS', 'CDHELP', 'STOOLDN1', 'VIRCOLO1', 'SMALSTOL', 'PSATEST1', 'HPVADSHT', 'CSRVINST', 'LOADULK2', 'CDDISCUS', 'CDSOCIAL', 'CDASSIST', 'CDHOUSE', 'CSRVCLIN', 'CSRVDEIN', 'CSRVINSR', 'CSRVRTRN', 'CSRVSUM', 'CSRVDOC1', 'COLNTES1', 'CRVCLPAP', 'CRVCLHPV', 'CRVCLCNC', 'COLNSIGM', 'CASTHNO2', 'CSRVTRT3', 'HOWLONG', 'COLNCNCR', 'HADSIGM4', 'CSRVPAIN', 'HADHYST2', 'CERVSCRN', 'HADMAM', 'CNCRTYP1', 'CNCRAGE', 'CNCRDIFF', 'HAVEHEPB', 'TOLDHEPC', 'LCSNUMCG', 'LCSLAST', 'GUNLOAD', 'LCSFIRST', 'HPVADVC4', 'RSNMRJN2', 'USEMRJN3', 'SHINGLE2', 'TETANUS1', 'FEETCHK', 'DIABEDU', 'DIABEYE', 'EYEEXAM1', 'CHKHEMO3', 'DOCTDIAB', 'FEETCHK3', 'INSULIN1', 'BLDSUGAR', 'STOPSMK2', 'LCSCTSCN', 'FIREARM5', 'NUMPHON3', 'CIMEMLOS', 'CRGVALZD', 'DRADVISE', 'WTCHSA

In [9]:
data1 = data1.drop(columns=['IDATE', 'IMONTH', 'IDAY', 'IYEAR','_STATE','FMONTH','DISPCODE','SEQNO','_PSU'])
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Columns: 130 entries, SEXVAR to CVD_LABEL
dtypes: float64(129), object(1)
memory usage: 435.1+ MB


In [10]:
# Cara 1 - List semua nama kolom
print(data1.columns.tolist())


['SEXVAR', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'PRIMINSR', 'PERSDOC3', 'MEDCOST1', 'CHECKUP1', 'EXERANY2', 'BPHIGH6', 'CHOLCHK3', 'TOLDHI3', 'CHOLMED3', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'CHCSCNCR', 'CHCOCNCR', 'CHCCOPD3', 'ADDEPEV3', 'CHCKDNY2', 'DIABETE4', 'HAVARTH5', 'MARITAL', 'EDUCA', 'RENTHOM1', 'CPDEMO1B', 'VETERAN3', 'EMPLOY1', 'CHILDREN', 'INCOME3', 'WEIGHT2', 'HEIGHT3', 'DEAF', 'BLIND', 'DECIDE', 'DIFFWALK', 'DIFFDRES', 'DIFFALON', 'SMOKE100', 'USENOW3', 'ECIGNOW1', 'ALCDAY5', 'FLUSHOT7', 'PNEUVAC4', 'HIVTST7', 'FRUIT2', 'FRUITJU2', 'FVGREEN1', 'FRENCHF1', 'POTATOE1', 'VEGETAB2', 'QSTVER', 'QSTLANG', '_METSTAT', '_URBSTAT', '_STSTR', '_STRWT', '_RAWRAKE', '_WT2RAKE', '_IMPRACE', '_DUALUSE', '_LLCPWT2', '_LLCPWT', '_RFHLTH', '_PHYS14D', '_MENT14D', '_HLTHPLN', '_HCVU652', '_TOTINDA', '_RFHYPE6', '_CHOLCH3', '_RFCHOL3', '_MICHD', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR3', '_LMTACT3', '_LMTWRK3', '_PRACE1', '_MRACE1', '_HISPANC', '_RACE', '_RACEG21', '_RACEGR3',

In [11]:
# Cara 4 - Dalam bentuk DataFrame (paling mudah dibaca)
pd.DataFrame({
    'Kolom': data1.columns,
    'Tipe Data': data1.dtypes.values,
    'Missing (%)': (data1.isnull().mean() * 100).round(2).values
})

,Kolom,Tipe Data,Missing (%)
0,SEXVAR,float64,0.0
1,GENHLTH,float64,0.0
2,PHYSHLTH,float64,0.0
3,MENTHLTH,float64,0.0
4,PRIMINSR,float64,0.0
...,...,...,...
125,_FRT16A,float64,0.0
126,_VEG23A,float64,0.0
127,_FRUITE1,float64,0.0
128,_VEGETE1,float64,0.0


In [12]:
# Cara 1 - Value counts semua kolom sekaligus
for col in data1.columns:
    print(f"\n{'='*50}")
    print(f"Kolom: {col}")
    print(data1[col].value_counts(dropna=False))


Kolom: SEXVAR
SEXVAR
2.0    234883
1.0    203810
Name: count, dtype: int64

Kolom: GENHLTH
GENHLTH
2.0    149112
3.0    137938
1.0     77741
4.0     54736
5.0     18005
7.0       788
9.0       369
NaN         4
Name: count, dtype: int64

Kolom: PHYSHLTH
PHYSHLTH
88.0    287796
30.0     29732
2.0      22220
1.0      17063
3.0      12868
5.0      11642
10.0      8595
77.0      7898
15.0      7623
4.0       6821
7.0       6695
20.0      4670
14.0      3994
6.0       1901
25.0      1866
99.0      1593
8.0       1254
21.0       927
12.0       813
28.0       671
9.0        302
29.0       279
18.0       253
16.0       222
17.0       158
27.0       155
13.0       126
22.0       120
11.0       119
26.0       108
24.0        98
23.0        65
19.0        43
NaN          3
Name: count, dtype: int64

Kolom: MENTHLTH
MENTHLTH
88.0    271161
30.0     24953
2.0      22717
5.0      19130
3.0      14567
10.0     14554
15.0     13475
1.0      13091
20.0      7993
7.0       7428
4.0       7419
77.0     

In [13]:
print(data1['_MISFRT1'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 438693 entries, 0 to 438692
Series name: _MISFRT1
Non-Null Count   Dtype  
--------------   -----  
438693 non-null  float64
dtypes: float64(1)
memory usage: 3.3 MB
None


In [14]:
data1['FRNCHDA_']

0         4.300000e+01
1         5.397605e-79
2         1.400000e+01
3         5.700000e+01
4         2.900000e+01
              ...     
438688    1.400000e+01
438689    1.400000e+01
438690    5.397605e-79
438691    5.397605e-79
438692    3.000000e+00
Name: FRNCHDA_, Length: 438693, dtype: float64

In [15]:
data1['_LLCPWT']

0          744.745531
1          299.137394
2          587.862986
3         1099.621573
4         1711.825866
             ...     
438688      40.447376
438689       8.291726
438690      99.135895
438691      13.653218
438692       8.805340
Name: _LLCPWT, Length: 438693, dtype: float64

In [16]:
# # 1. Ganti nilai aneh (hampir 0) jadi 0
# import numpy as np
# data1['FRNCHDA_'] = data1['FRNCHDA_'].apply(lambda x: 0 if (pd.notna(x) and x < 1e-10) else x)

# # 2. Bagi 100 karena two implied decimal places
# data1['FRNCHDA_'] = data1['FRNCHDA_'] / 100

# # 3. NaN = missing (Don't know/Refused), biarkan atau isi sesuai kebutuhan

In [17]:
data1['FRNCHDA_']

0         4.300000e+01
1         5.397605e-79
2         1.400000e+01
3         5.700000e+01
4         2.900000e+01
              ...     
438688    1.400000e+01
438689    1.400000e+01
438690    5.397605e-79
438691    5.397605e-79
438692    3.000000e+00
Name: FRNCHDA_, Length: 438693, dtype: float64

In [18]:
severity_map = {
    'Healt'            : 0,  # Sehat
    'Stroke Only'       : 1,  # Level 1 → 1 kondisi
    'CHD Only'          : 1,  # Level 1 → 1 kondisi
    'Heart Attack Only' : 1,  # Level 1 → 1 kondisi
    'MI + CHD'          : 2,  # Level 2 → 2 kondisi
    'MI + Stroke'       : 2,  # Level 2 → 2 kondisi
    'CHD + Stroke'      : 2,  # Level 2 → 2 kondisi
    'All Three'         : 3,  # Level 3 → 3 kondisi
}

data1['CVD_SEVERITY'] = data1['CVD_LABEL'].map(severity_map)

# Verifikasi
print(data1['CVD_SEVERITY'].value_counts())
print(f"\nTotal : {len(data1):,}")

CVD_SEVERITY
0    391852
1     32861
2     11866
3      2114
Name: count, dtype: int64

Total : 438,693


In [19]:
data1["CVD_LABEL"].value_counts()

CVD_LABEL
Healt                391852
Stroke Only           11518
CHD Only              11048
Heart Attack Only     10295
MI + CHD               8285
MI + Stroke            2137
All Three              2114
CHD + Stroke           1444
Name: count, dtype: int64

In [20]:
data1 = data1.drop(columns=['_VEGRES1','_FRTRES1','_MISVEG1','_MISFRT1','CVD_LABEL'])
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Columns: 126 entries, SEXVAR to CVD_SEVERITY
dtypes: float64(125), int64(1)
memory usage: 421.7 MB


In [21]:
# Cek null semua kolom
null_summary = pd.DataFrame({
    'null_count': data1.isnull().sum(),
    'null_percent': (data1.isnull().sum() / len(data1) * 100).round(2)
}).sort_values('null_percent', ascending=False)

print(null_summary[null_summary['null_count'] > 0])

          null_count  null_percent
CHOLMED3       61571         14.04
_RFCHOL3       61151         13.94
TOLDHI3        60836         13.87
_VEGESU1       60127         13.71
_FRUTSU1       51087         11.65
...              ...           ...
PHYSHLTH           3          0.00
HAVARTH5           3          0.00
EDUCA              5          0.00
RENTHOM1           8          0.00
GENHLTH            4          0.00

[75 rows x 2 columns]


In [23]:
data_new = data1.dropna()
print(f"Sebelum : {len(data1)} baris")
print(f"Sesudah : {len(data_new)} baris")
print(f"Terhapus: {len(data1) - len(data_new)} baris")

Sebelum : 438693 baris
Sesudah : 289586 baris
Terhapus: 149107 baris


In [24]:
data_new

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,PRIMINSR,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPHIGH6,...,VEGEDA2_,_FRUTSU1,_VEGESU1,_FRTLT1A,_VEGLT1A,_FRT16A,_VEG23A,_FRUITE1,_VEGETE1,CVD_SEVERITY
0,2.0,5.0,20.0,10.0,3.0,1.0,2.0,2.0,2.0,3.0,...,100.0,100.0,214.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
2,2.0,2.0,88.0,88.0,2.0,2.0,2.0,1.0,2.0,1.0,...,43.0,100.0,71.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,1
3,2.0,2.0,88.0,10.0,2.0,1.0,2.0,1.0,1.0,1.0,...,71.0,114.0,165.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
4,1.0,5.0,30.0,88.0,3.0,1.0,2.0,1.0,1.0,4.0,...,100.0,100.0,258.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,2
5,1.0,3.0,88.0,88.0,3.0,1.0,2.0,1.0,2.0,3.0,...,14.0,29.0,42.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431633,2.0,3.0,88.0,88.0,88.0,3.0,2.0,4.0,2.0,2.0,...,100.0,29.0,200.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
431634,2.0,3.0,30.0,88.0,1.0,2.0,1.0,1.0,2.0,3.0,...,57.0,107.0,122.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
431635,1.0,3.0,88.0,88.0,1.0,1.0,2.0,2.0,1.0,3.0,...,100.0,16.0,257.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
431636,1.0,4.0,10.0,88.0,3.0,1.0,2.0,1.0,2.0,3.0,...,100.0,100.0,207.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0


In [48]:
# Pastikan semua kolom ini tidak ada
forbidden = ['_MICHD', 'CVDSTRK3', 'CVDCRHD4', 'CVDINFR4']
data_new = data_new.drop(columns=forbidden)
for col in forbidden:
    if col in data_new.columns:
        print(f"⚠️  MASIH ADA: {col}")
    else:
        print(f"✅ Sudah dihapus: {col}")

✅ Sudah dihapus: _MICHD
✅ Sudah dihapus: CVDSTRK3
✅ Sudah dihapus: CVDCRHD4
✅ Sudah dihapus: CVDINFR4


In [49]:
X = data_new.drop(columns=['CVD_SEVERITY'])
y = data_new['CVD_SEVERITY']

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


In [ ]:
from xgboost import XGBClassifier
import numpy as np

### Feature Selection

In [53]:
# ============================================================
# STEP 3 & 4: Feature Selection dengan XGBoost
# ============================================================
xgb_fs = XGBClassifier(
    n_estimators=100,
    random_state=42,
    eval_metric='mlogloss',
    use_label_encoder=False
)
xgb_fs.fit(X_train, y_train)

importances = xgb_fs.feature_importances_
feature_names = list(X_train.columns) if hasattr(X_train, 'columns') else [f"feature_{i}" for i in range(X_train.shape[1])]

feat_df = pd.DataFrame({
    'feature': feature_names,
    'importance': importances
}).sort_values('importance', ascending=False)

print("\nTop 10 fitur berdasarkan XGBoost importance:")
print(feat_df.head(10).to_string(index=False))

TOP_K = 20

# ✅ FIX: Ambil nama fitur, bukan index dari feat_df
selected_features = feat_df.head(TOP_K)['feature'].tolist()

# ✅ FIX: Gunakan .loc[] untuk DataFrame, atau konversi ke numpy dulu
if hasattr(X_train, 'columns'):
    # Jika DataFrame
    X_train_fs = X_train[selected_features].values
    X_test_fs  = X_test[selected_features].values
else:
    # Jika sudah numpy array
    selected_idx = feat_df.head(TOP_K).index.tolist()
    X_train_fs = np.array(X_train)[:, selected_idx]
    X_test_fs  = np.array(X_test)[:, selected_idx]

print(f"\nFitur dipilih: {TOP_K} dari {X_train.shape[1]}")
print(f"Shape setelah FS: {X_train_fs.shape}")

/opt/homebrew/lib/python3.11/site-packages/xgboost/training.py:183: UserWarning: [20:58:30] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)



Top 10 fitur berdasarkan XGBoost importance:
 feature  importance
CHOLMED3    0.174993
 GENHLTH    0.053323
_RFHYPE6    0.050100
DIFFWALK    0.044612
 EMPLOY1    0.031191
    _SEX    0.022943
  _AGE80    0.021082
_AGEG5YR    0.020987
 BPHIGH6    0.018375
  SEXVAR    0.016084

Fitur dipilih: 20 dari 121
Shape setelah FS: (231668, 20)


In [54]:
print(pd.Series(y_train).value_counts())

CVD_SEVERITY
0    204397
1     18929
2      7096
3      1246
Name: count, dtype: int64


## Training dan Prepocessing Model 

In [55]:
# Cek class apa saja yang ada di data
print("Classes di y_train:", sorted(y_train.unique()))
print("Classes di y_test :", sorted(y_test.unique()))
print("Jumlah class       :", y_test.nunique())

Classes di y_train: [0, 1, 2, 3]
Classes di y_test : [0, 1, 2, 3]
Jumlah class       : 4


In [56]:
from sklearn.metrics import (
    accuracy_score, classification_report,
    roc_auc_score, confusion_matrix,f1_score
)
 
# ── Ensemble Models ─────────────────────────────────────────────────────────
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    ExtraTreesClassifier,
)

from lightgbm import LGBMClassifier


In [57]:
n_classes = 4

In [58]:
models = {
 
    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        max_features="sqrt",
        class_weight="balanced",   # bagus jika kelas tidak seimbang
        n_jobs=-1,
        random_state=42,
    ),
 
    "XGBoost": XGBClassifier(
        objective="multi:softprob",   # ← wajib untuk multi-class
        num_class=n_classes,          # ← jumlah kelas
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        use_label_encoder=False,
        eval_metric="mlogloss",       # ← multi-class log loss
        random_state=42,
        verbosity=0,
    ),
 
    # "GBM (Gradient Boosting)": GradientBoostingClassifier(
    #     # scikit-learn GBM otomatis pakai One-vs-Rest untuk multi-class
    #     n_estimators=300,
    #     learning_rate=0.05,
    #     max_depth=4,
    #     subsample=0.8,
    #     min_samples_split=2,
    #     min_samples_leaf=1,
    #     random_state=42,
    # ),
 
    "LightGBM": LGBMClassifier(
        objective="multiclass",       # ← wajib untuk multi-class
        num_class=n_classes,          # ← jumlah kelas
        n_estimators=300,
        learning_rate=0.05,
        max_depth=-1,
        num_leaves=31,
        subsample=0.8,
        colsample_bytree=0.8,
        class_weight="balanced",
        n_jobs=-1,
        random_state=42,
        verbose=-1,
    ),
 
    "Extra Trees": ExtraTreesClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        max_features="sqrt",
        class_weight="balanced",
        n_jobs=-1,
        random_state=42,
    ),
}
 

In [ ]:
# ============================================================
# FUNCTION: Train & Evaluate
# ============================================================
def train_evaluate(
    models: dict,
    X_train, y_train,
    X_test,  y_test,
    dataset_label: str = "default",     # nama dataset, misal "smotenn", "ctgan", "raw"
    export_csv: bool   = True,
    target_names: list = ['0','1','2','3']
):
    results     = {}
    summary_rows = []

    for name, model in models.items():
        print(f"\n🔧 Training: {name} | Dataset: {dataset_label} ...")

        # ── Fit ──────────────────────────────────────────────
        model.fit(X_train, y_train)

        # ── Predict ──────────────────────────────────────────
        y_pred  = model.predict(X_test)
        y_proba = model.predict_proba(X_test)

        # ── Metrics ──────────────────────────────────────────
        acc     = accuracy_score(y_test, y_pred)
        f1      = f1_score(y_test, y_pred, average='macro')
        auc     = roc_auc_score(y_test, y_proba, multi_class='ovr', average='macro')
        cm      = confusion_matrix(y_test, y_pred)
        report  = classification_report(y_test, y_pred, target_names=target_names)

        # ── Simpan detail ─────────────────────────────────────
        results[name] = {
            "model"          : model,
            "Accuracy"       : acc,
            "F1-Score"       : f1,
            "ROC-AUC"        : auc,
            "confusion_matrix": cm,
            "report"         : report,
            "dataset"        : dataset_label,
        }

        summary_rows.append({
            "Model"        : name,
            "Dataset"      : dataset_label,
            "Accuracy"     : round(acc, 4),
            "F1-Score"     : round(f1,  4),
            "ROC-AUC"      : round(auc, 4),
        })

        # ── Print ─────────────────────────────────────────────
        print(f"   ✅ Accuracy: {acc:.4f}  |  F1-Score: {f1:.4f}  |  ROC-AUC: {auc:.4f}")
        print(f"\nConfusion Matrix:\n{cm}")
        print(f"\nClassification Report:\n{report}")

    # ── Buat DataFrame ringkasan ──────────────────────────────
    results_df = pd.DataFrame(summary_rows)

    # ── Export CSV ────────────────────────────────────────────
    if export_csv:
        filename = f"hasil_evaluasi_{dataset_label}.csv"
        results_df.to_csv(filename, index=False)
        print(f"\n📁 Hasil disimpan → {filename}")

    return results_df, results

In [ ]:
from imblearn.over_sampling import SMOTE, ADASYN
# ── SMOTE FS ─────────────────────────────────────────────────────────────────────
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_fs, y_train)
print(f"SMOTE → {sorted(dict(zip(*np.unique(y_train_smote, return_counts=True))).items())}")

# ── ADASYN FS ────────────────────────────────────────────────────────────────────
adasyn = ADASYN(random_state=42)
X_train_adasyn, y_train_adasyn = adasyn.fit_resample(X_train_fs, y_train)
print(f"ADASYN → {sorted(dict(zip(*np.unique(y_train_adasyn, return_counts=True))).items())}")


# ── SMOTE Non FS─────────────────────────────────────────────────────────────────────
X_train_smote_nonFs, y_train_smote_nonFs = smote.fit_resample(X_train, y_train)
print(f"SMOTE → {sorted(dict(zip(*np.unique(y_train_smote_nonFs, return_counts=True))).items())}")

# ── ADASYN Non FS ────────────────────────────────────────────────────────────────────
X_train_adasyn_nonFs, y_train_adasyn_nonFs = adasyn.fit_resample(X_train, y_train)
print(f"ADASYN → {sorted(dict(zip(*np.unique(y_train_adasyn_nonFs, return_counts=True))).items())}")

SMOTE → [(0, 204397), (1, 204397), (2, 204397), (3, 204397)]
ADASYN → [(0, 204397), (1, 201948), (2, 203403), (3, 204542)]


In [ ]:
from imblearn.combine import SMOTEENN
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import BorderlineSMOTE

smote = SMOTEENN(random_state=42)
X_train_smotenn, y_train_smotenn = smote.fit_resample(X_train_fs, y_train)

smote = SMOTETomek(random_state=42)
X_train_smotetomek, y_train_smottomek = smote.fit_resample(X_train_fs, y_train)

bsmote = BorderlineSMOTE(
    kind='borderline-1',  # atau 'borderline-2'
    random_state=42
)

X_train_bsmote, y_train_bsmote = bsmote.fit_resample(X_train_fs, y_train)

# ---- Non FS ---
X_train_smotenn_nonFs, y_train_smotenn_nonFs = smote.fit_resample(X_train, y_train)

X_train_smotetomek_nonFs, y_train_smottomek_nonFs = smote.fit_resample(X_train, y_train)

X_train_bsmote_nonFs, y_train_bsmote_nonFs = bsmote.fit_resample(X_train, y_train)


In [ ]:
# ── Pakai SMOTEENN ────────────────────────────────────────────────
# ── SMOTEENN ──────────────────────────────────────────────────────────────────
df_smoteenn, res_smoteenn = train_evaluate(
    models=models, X_train=X_train_smotenn, y_train=y_train_smotenn,
    X_test=X_test_fs, y_test=y_test, dataset_label="smoteenn",
)

# ── SMOTETomek ────────────────────────────────────────────────────────────────
df_smotetomek, res_smotetomek = train_evaluate(
    models=models, X_train=X_train_smotetomek, y_train=y_train_smottomek,
    X_test=X_test_fs, y_test=y_test, dataset_label="smotetomek",
)

# ── Pakai data borderliane  ─────────────────────────────
df_raw, res_raw = train_evaluate(
    models       = models,
    X_train      = X_train_bsmote,
    y_train      = y_train_bsmote,
    X_test       = X_test_fs,
    y_test       = y_test,
    dataset_label= "borderline Smote",
)

# ── Pakai data raw (tanpa balancing) ─────────────────────────────
df_raw_1, res_raw_1 = train_evaluate(
    models       = models,
    X_train      = X_train_fs,
    y_train      = y_train,
    X_test       = X_test_fs,
    y_test       = y_test,
    dataset_label= "raw2",
)


🔧 Training: Random Forest | Dataset: raw ...


/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


   ✅ Accuracy: 0.8823  |  F1-Score: 0.2344  |  ROC-AUC: 0.8401

Confusion Matrix:
[[51100     0     0     0]
 [ 4732     0     0     0]
 [ 1774     0     0     0]
 [  312     0     0     0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.00      0.00      0.00      4732
           2       0.00      0.00      0.00      1774
           3       0.00      0.00      0.00       312

    accuracy                           0.88     57918
   macro avg       0.22      0.25      0.23     57918
weighted avg       0.78      0.88      0.83     57918


🔧 Training: XGBoost | Dataset: raw ...
   ✅ Accuracy: 0.8820  |  F1-Score: 0.2601  |  ROC-AUC: 0.8598

Confusion Matrix:
[[50926   137    37     0]
 [ 4586   112    34     0]
 [ 1630   100    43     1]
 [  263    35    12     2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      1.00      0

/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


   ✅ Accuracy: 0.8821  |  F1-Score: 0.2486  |  ROC-AUC: 0.8515

Confusion Matrix:
[[51007    57    36     0]
 [ 4656    49    27     0]
 [ 1692    48    34     0]
 [  283    15    14     0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.29      0.01      0.02      4732
           2       0.31      0.02      0.04      1774
           3       0.00      0.00      0.00       312

    accuracy                           0.88     57918
   macro avg       0.37      0.26      0.25     57918
weighted avg       0.81      0.88      0.83     57918


🔧 Training: LightGBM | Dataset: raw2 ...


/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


   ✅ Accuracy: 0.6643  |  F1-Score: 0.3120  |  ROC-AUC: 0.8144

Confusion Matrix:
[[36097  9086  3853  2064]
 [ 1010  1649  1171   902]
 [  154   498   599   523]
 [   15    74    94   129]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.71      0.82     51100
           1       0.15      0.35      0.21      4732
           2       0.10      0.34      0.16      1774
           3       0.04      0.41      0.07       312

    accuracy                           0.66     57918
   macro avg       0.31      0.45      0.31     57918
weighted avg       0.87      0.66      0.74     57918


🔧 Training: Extra Trees | Dataset: raw2 ...
   ✅ Accuracy: 0.7702  |  F1-Score: 0.2957  |  ROC-AUC: 0.6922

Confusion Matrix:
[[43404  4909  2193   594]
 [ 3049   911   580   192]
 [ 1007   385   280   102]
 [  194    62    42    14]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.85  

In [ ]:
# ── SMOTE ─────────────────────────────────────────────────────────────────────
df_smote, res_smote = train_evaluate(
    models=models, X_train=X_train_smote, y_train=y_train_smote,
    X_test=X_test_fs, y_test=y_test, dataset_label="smote",
)

# ── ADASYN ────────────────────────────────────────────────────────────────────
df_adasyn, res_adasyn = train_evaluate(
    models=models, X_train=X_train_adasyn, y_train=y_train_adasyn,
    X_test=X_test_fs, y_test=y_test, dataset_label="adasyn",
)


🔧 Training: Random Forest | Dataset: smote ...
   ✅ Accuracy: 0.8304  |  F1-Score: 0.3135  |  ROC-AUC: 0.7566

Confusion Matrix:
[[47011  3076   929    84]
 [ 3448   865   380    39]
 [ 1113   414   217    30]
 [  189    78    40     5]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.92      0.91     51100
           1       0.20      0.18      0.19      4732
           2       0.14      0.12      0.13      1774
           3       0.03      0.02      0.02       312

    accuracy                           0.83     57918
   macro avg       0.32      0.31      0.31     57918
weighted avg       0.82      0.83      0.83     57918


🔧 Training: XGBoost | Dataset: smote ...
   ✅ Accuracy: 0.8213  |  F1-Score: 0.3502  |  ROC-AUC: 0.8283

Confusion Matrix:
[[46069  3365  1495   171]
 [ 2906  1013   698   115]
 [  814   411   461    88]
 [  136    70    80    26]]

Classification Report:
              precision    recall  f1-score  

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


   ✅ Accuracy: 0.8454  |  F1-Score: 0.3362  |  ROC-AUC: 0.8293

Confusion Matrix:
[[47869  2170   992    69]
 [ 3426   720   541    45]
 [ 1059   315   363    37]
 [  186    52    63    11]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.94      0.92     51100
           1       0.22      0.15      0.18      4732
           2       0.19      0.20      0.19      1774
           3       0.07      0.04      0.05       312

    accuracy                           0.85     57918
   macro avg       0.35      0.33      0.34     57918
weighted avg       0.83      0.85      0.84     57918


🔧 Training: Extra Trees | Dataset: smote ...
   ✅ Accuracy: 0.8312  |  F1-Score: 0.3112  |  ROC-AUC: 0.7149

Confusion Matrix:
[[47112  2959   930    99]
 [ 3511   814   365    42]
 [ 1166   359   213    36]
 [  195    70    42     5]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.92 

### Non Feature Selection

In [ ]:


# ── Pakai SMOTEENN ────────────────────────────────────────────────
# ── SMOTEENN ──────────────────────────────────────────────────────────────────
train_evaluate(
    models=models, X_train=X_train_smotenn_nonFs, y_train=y_train_smotenn_nonFs,
    X_test=X_test, y_test=y_test, dataset_label="smoteenn_nonFs",
)

# ── SMOTETomek ────────────────────────────────────────────────────────────────
train_evaluate(
    models=models, X_train=X_train_smotetomek_nonFs, y_train=y_train_smottomek_nonFs,
    X_test=X_test, y_test=y_test, dataset_label="smotetomek_nonFs",
)

# ── Pakai data borderliane  ─────────────────────────────
train_evaluate(
    models       = models,
    X_train      = X_train_bsmote_nonFs,
    y_train      = y_train_bsmote_nonFs,
    X_test       = X_test,
    y_test       = y_test,
    dataset_label= "borderline Smote_nonFs",
)

# ── Pakai data raw (tanpa balancing) ─────────────────────────────
train_evaluate(
    models       = models,
    X_train      = X_train,
    y_train      = y_train,
    X_test       = X_test,
    y_test       = y_test,
    dataset_label= "raw2_nonFs",
)


NameError: name 'train_evaluate' is not defined

In [ ]:
# ── SMOTE ─────────────────────────────────────────────────────────────────────
train_evaluate(
    models=models, X_train=X_train_smote_nonFs, y_train=y_train_smote_nonFs,
    X_test=X_test, y_test=y_test, dataset_label="smote_nonFs",
)

# ── ADASYN ────────────────────────────────────────────────────────────────────
df_adasyn, res_adasyn = train_evaluate(
    models=models, X_train=X_train_adasyn_nonFs, y_train=y_train_adasyn_nonFs,
    X_test=X_test, y_test=y_test, dataset_label="adasyn_nonFS",
)